Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -5,12 +5,17 @@ on:
     branches: [ "main" ]
   workflow_dispatch:
 
+env:
+  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
+
 jobs:
   build:
     runs-on: ubuntu-latest
+    timeout-minutes: 20
+    
     steps:
       - name: Checkout Code
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           path: 'sqm-src'
 
@@ -20,8 +25,11 @@ jobs:
 
       - name: Download OpenWrt SDK
         run: |
+          sudo apt-get update
+          sudo apt-get install -y zstd
           wget -qO sdk.tar.zst "https://downloads.openwrt.org/releases/24.10.0/targets/rockchip/armv8/openwrt-sdk-24.10.0-rockchip-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst"
-          mkdir openwrt-sdk && tar -I zstd -xf sdk.tar.zst -C openwrt-sdk --strip-components=1
+          mkdir openwrt-sdk
+          tar -I zstd -xf sdk.tar.zst -C openwrt-sdk --strip-components=1
 
       - name: Prepare Package and Build
         run: |
@@ -37,8 +45,18 @@ jobs:
           make defconfig
           make package/sqm-scripts-nft/compile V=s
 
+          IPK_FILE=$(find bin/packages/ -name "sqm-scripts-nft*.ipk" | head -n 1)
+          
+          if [ -z "$IPK_FILE" ]; then
+            echo "Error: IPK file not found after build."
+            exit 1
+          fi
+          
+          echo "ipk_path=openwrt-sdk/$IPK_FILE" >> $GITHUB_ENV
+
       - name: Upload Artifact
-        uses: actions/upload-artifact@v4
+        uses: actions/upload-artifact@v7
         with:
           name: sqm-nft-24.10.0-build-${{ github.run_number }}
-          path: openwrt-sdk/bin/packages/*/base/*.ipk
+          path: ${{ env.ipk_path }}
+          if-no-files-found: error
